### ISSUE TITLE
Roadmap for 1.0.0

### ISSUE THREAD

**Issue by machty** [machty/ember-concurrency#214]
e-c's been stable for a while, probably time to make it 1.0.0. Here's some things I'd like to try and address before then (and please feel free to comment and link to important not-yet-addressed existing issues):

- [ ] Better testing solution / methodology for timer loops and slow timers, possibly involving ember-milestones
- [ ] (possibly) changing the behavior of error handling: it's really crappy that we populate the `.error` field on the task instance AND we still bubble the error out of the run loop. Error handling is hard but it's one of the dumber behaviors/apis in e-c
  - proposals/idea: [Selective error bubbling](https://github.com/machty/ember-concurrency/pull/157)
  - pattern: [marking error as handled, ignored in Ember.onerror](https://github.com/machty/ember-concurrency/issues/40#issuecomment-306929665)
- [x] fix waitFor* not working with race() and other promise helpers
    

...and many more (i think): please help me fill this out.

**Comment by maxfierke** [comment]
This race condition issue seems like it might be a good candidate: https://github.com/machty/ember-concurrency/issues/132

**Comment by BryanCrotaz** [comment]
Timer loops. I have a lot of watchdogs in my app:

Watchdog: task(function*() {
  while(true) {
    yield timeout(1000);
    if (!this.connected) {
      this.reconnect();
    }
  }
})

This is impossible to test. How about 

watchdog:task(function *() {
  if (!this.connected) {
      this.reconnect();
    }
}).poll(1000);

Next question is how you’d check this in a test...

**Comment by bartocc** [comment]
+1 on error handling. I am often confused about how to use the try/catch blocks with my tasks

**Comment by lindyhopchris** [comment]
Awesome to see plan to get to 1.0. Can #181 be on the list? We extensively use racing between either a success or error event broadcast over a websocket, so fixing this issue would be a huge plus.

**Comment by machty** [comment]
@lindyhopchris just published a fix for #181

**Comment by lindyhopchris** [comment]
@machty great, thanks!

**Comment by maxfierke** [comment]
One idea: deprecate the `perform` helper. Because tasks can be passed to the `action` helper, it seems like there's not much of a reason to keep it around?

**Comment by buschtoens** [comment]
@maxfierke You mean something like?

```hbs
<button onclick={{action deleteUser.perform user}}>
  Delete {{user.name}}
</button>
```

**Comment by maxfierke** [comment]
@buschtoens as it stands now, you can just pass `deleteUser` as the action and it will be performed

**Comment by buschtoens** [comment]
This I did not know. Awesome!

This'll probably not be easy to do, but getting rid of `.perform()` completely has been on my wish list for quite some time now.

**Comment by maxfierke** [comment]
It seems like something that _might_ be codemod-able?

**Comment by buschtoens** [comment]
I meant getting rid of `.perform()` in JS land. So that the CP itself would be a function that calls `.perform()` (with all the other stuff slapped on to it, like `.cancelAll()`).

**Comment by maxfierke** [comment]
@buschtoens that would be doable with #218 (except the `.cancelAll` bit, since it returns a `TaskInstance`)

**Comment by buschtoens** [comment]
I created #240 as to not further derail the convo about 1.0.0 blockers here. 😅

**Comment by jrjohnson** [comment]
This is a great list, but I'd like to put a vote up for declaring 1.0 right now and addressing these as time permits possibly for 2.0 if they are breaking. Or 3.0, or 4.0 😜 

Tons of apps and addons are using this in production now which points to it's stability and the reasonableness of a 1.0 designation, but it also makes it a primary source of conflicts for us when using `ember-cli-dependency-lint`.

The reason is that an addon which declares `"ember-concurrency": "^0.8.0",` needs to be updated for `0.9` and `0.10`, whereas declaring `"ember-concurrency": "^1.0",` would allow NPM to just resolve these conflicts automatically giving the latest version in most cases.

**Comment by Turbo87** [comment]
I suppose since v1.0.0 has been released a while ago we can close this issue?

**Comment by maxfierke** [comment]
Good point. I've thought about this thread as less about a specific release and more of a wishlist for  solutions to specific painpoints. But perhaps those should be separate issues anyway.
